### ISSUE TITLE
XQuery Update statement

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sebbae/brackit#7]
Hi Sebastian,

I have an XQuery Update statement as follows. I think I have two problems. Do you know how I can bind namespace prefixes?

And second I'm getting the exception:
org.brackit.xquery.QueryException: err:XPDY0002: Dynamic context variable fs:dot is not assigned a value
	at org.brackit.xquery.expr.DefaultCtxItem.evaluateToItem(DefaultCtxItem.java:95)
	at org.brackit.xquery.expr.DefaultCtxItem.evaluate(DefaultCtxItem.java:78)

after commenting

    // throw new QueryException(ErrorCode.ERR_UNDEFINED_NAMESPACE_PREFIX,
    // "Undefined namespace prefix: '%s'", prefix);

in AbstractAnalyser.

let $doc := sdb:doc('path1','shredded', 1)
return (
  rename node sdb:select-node($doc, 1) as <worksheet/>,
  delete nodes sdb:select-node($doc, 6),
  delete nodes sdb:select-node($doc, 7),
  insert node attribute mc:Ignorable { x14ac } into sdb:select-node($doc,1),
  rename node sdb:select-node($doc, 22) as <cols/>,
  rename node sdb:select-node($doc, 23) as <col/>,
  insert node attribute width { 5 } into sdb:select-node($doc,23),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,23),
  delete nodes sdb:select-node($doc, 23),
  delete nodes sdb:select-node($doc, 23),
  delete nodes sdb:select-node($doc, 23),
  delete nodes sdb:select-node($doc, 27),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 27),
  delete nodes sdb:select-node($doc, 27),
  delete nodes sdb:select-node($doc, 27),
  delete nodes sdb:select-node($doc, 33),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 33),
  delete nodes sdb:select-node($doc, 33),
  delete nodes sdb:select-node($doc, 33),
  delete nodes sdb:select-node($doc, 39),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 39),
  delete nodes sdb:select-node($doc, 39),
  delete nodes sdb:select-node($doc, 39),
  delete nodes sdb:select-node($doc, 45),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 45),
  delete nodes sdb:select-node($doc, 45),
  delete nodes sdb:select-node($doc, 45),
  delete nodes sdb:select-node($doc, 51),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 51),
  delete nodes sdb:select-node($doc, 51),
  delete nodes sdb:select-node($doc, 51),
  delete nodes sdb:select-node($doc, 57),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 57),
  delete nodes sdb:select-node($doc, 57),
  delete nodes sdb:select-node($doc, 57),
  delete nodes sdb:select-node($doc, 63),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 63),
  delete nodes sdb:select-node($doc, 63),
  delete nodes sdb:select-node($doc, 63),
  delete nodes sdb:select-node($doc, 69),
  insert node attribute customWidth { 1 } into sdb:select-node($doc,74),
  insert node attribute min { 2 } into sdb:select-node($doc,74),
  insert node attribute max { 2 } into sdb:select-node($doc,74),
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 69),
  delete nodes sdb:select-node($doc, 69),
  rename node sdb:select-node($doc, 74) as <col/>,
  insert node attribute width { 19.85546875 } into sdb:select-node($doc,74),
  insert node attribute bestFit { 1 } into sdb:select-node($doc,74),
  delete nodes sdb:select-node($doc, 74),
  delete nodes sdb:select-node($doc, 74),
  delete nodes sdb:select-node($doc, 74),
  delete nodes sdb:select-node($doc, 78),
  delete nodes sdb:select-node($doc, 78),
  delete nodes sdb:select-node($doc, 78),
  delete nodes sdb:select-node($doc, 83),
  delete nodes sdb:select-node($doc, 83),
  delete nodes sdb:select-node($doc, 83),
  delete nodes sdb:select-node($doc, 88),
  delete nodes sdb:select-node($doc, 88),
  delete nodes sdb:select-node($doc, 88),
  delete nodes sdb:select-node($doc, 88),
  delete nodes sdb:select-node($doc, 94),
  delete nodes sdb:select-node($doc, 94),
  delete nodes sdb:select-node($doc, 94),
  delete nodes sdb:select-node($doc, 94),
  delete nodes sdb:select-node($doc, 100),
  delete nodes sdb:select-node($doc, 100),
  delete nodes sdb:select-node($doc, 100),
  delete nodes sdb:select-node($doc, 100),
  delete nodes sdb:select-node($doc, 106),
  delete nodes sdb:select-node($doc, 106),
  delete nodes sdb:select-node($doc, 106),
  delete nodes sdb:select-node($doc, 111),
  delete nodes sdb:select-node($doc, 111),
  delete nodes sdb:select-node($doc, 111),
  delete nodes sdb:select-node($doc, 118),
  delete nodes sdb:select-node($doc, 118),
  delete nodes sdb:select-node($doc, 118),
  delete nodes sdb:select-node($doc, 118),
  delete nodes sdb:select-node($doc, 124),
  delete nodes sdb:select-node($doc, 124),
  delete nodes sdb:select-node($doc, 124),
  delete nodes sdb:select-node($doc, 124),
  delete nodes sdb:select-node($doc, 171),
  delete nodes sdb:select-node($doc, 171),
  delete nodes sdb:select-node($doc, 171),
  delete nodes sdb:select-node($doc, 171),
  delete nodes sdb:select-node($doc, 216),
  delete nodes sdb:select-node($doc, 216),
  delete nodes sdb:select-node($doc, 216),
  delete nodes sdb:select-node($doc, 216),
  delete nodes sdb:select-node($doc, 261),
  delete nodes sdb:select-node($doc, 261),
  delete nodes sdb:select-node($doc, 261),
  delete nodes sdb:select-node($doc, 261),
  delete nodes sdb:select-node($doc, 306),
  delete nodes sdb:select-node($doc, 306),
  delete nodes sdb:select-node($doc, 306),
  delete nodes sdb:select-node($doc, 306),
  delete nodes sdb:select-node($doc, 351),
  delete nodes sdb:select-node($doc, 351),
  delete nodes sdb:select-node($doc, 351),
  delete nodes sdb:select-node($doc, 351),
  delete nodes sdb:select-node($doc, 396),
  delete nodes sdb:select-node($doc, 396),
  delete nodes sdb:select-node($doc, 396),
  delete nodes sdb:select-node($doc, 396),
  delete nodes sdb:select-node($doc, 441),
  delete nodes sdb:select-node($doc, 441),
  delete nodes sdb:select-node($doc, 441),
  delete nodes sdb:select-node($doc, 441),
  delete nodes sdb:select-node($doc, 486),
  delete nodes sdb:select-node($doc, 486),
  delete nodes sdb:select-node($doc, 486),
  delete nodes sdb:select-node($doc, 486),
  delete nodes sdb:select-node($doc, 531),
  delete nodes sdb:select-node($doc, 531),
  delete nodes sdb:select-node($doc, 531),
  delete nodes sdb:select-node($doc, 531),
  delete nodes sdb:select-node($doc, 576),
  delete nodes sdb:select-node($doc, 576),
  delete nodes sdb:select-node($doc, 576),
  delete nodes sdb:select-node($doc, 576),
  delete nodes sdb:select-node($doc, 621),
  delete nodes sdb:select-node($doc, 621),
  delete nodes sdb:select-node($doc, 621),
  delete nodes sdb:select-node($doc, 621),
  delete nodes sdb:select-node($doc, 666),
  delete nodes sdb:select-node($doc, 666),
  delete nodes sdb:select-node($doc, 666),
  delete nodes sdb:select-node($doc, 666),
  delete nodes sdb:select-node($doc, 711),
  delete nodes sdb:select-node($doc, 711),
  delete nodes sdb:select-node($doc, 711),
  delete nodes sdb:select-node($doc, 711),
  delete nodes sdb:select-node($doc, 756),
  delete nodes sdb:select-node($doc, 756),
  delete nodes sdb:select-node($doc, 756),
  delete nodes sdb:select-node($doc, 756),
  delete nodes sdb:select-node($doc, 801),
  delete nodes sdb:select-node($doc, 801),
  delete nodes sdb:select-node($doc, 801),
  delete nodes sdb:select-node($doc, 801),
  delete nodes sdb:select-node($doc, 846),
  delete nodes sdb:select-node($doc, 846),
  delete nodes sdb:select-node($doc, 846),
  delete nodes sdb:select-node($doc, 846),
  delete nodes sdb:select-node($doc, 891),
  delete nodes sdb:select-node($doc, 891),
  delete nodes sdb:select-node($doc, 891),
  delete nodes sdb:select-node($doc, 891),
  delete nodes sdb:select-node($doc, 935),
  delete nodes sdb:select-node($doc, 935),
  delete nodes sdb:select-node($doc, 935),
  delete nodes sdb:select-node($doc, 935),
  delete nodes sdb:select-node($doc, 980),
  delete nodes sdb:select-node($doc, 980),
  delete nodes sdb:select-node($doc, 980),
  delete nodes sdb:select-node($doc, 980),
  delete nodes sdb:select-node($doc, 1025),
  delete nodes sdb:select-node($doc, 1025),
  delete nodes sdb:select-node($doc, 1025),
  delete nodes sdb:select-node($doc, 1025),
  delete nodes sdb:select-node($doc, 1070),
  delete nodes sdb:select-node($doc, 1070),
  delete nodes sdb:select-node($doc, 1070),
  delete nodes sdb:select-node($doc, 1070),
  delete nodes sdb:select-node($doc, 1115),
  delete nodes sdb:select-node($doc, 1115),
  delete nodes sdb:select-node($doc, 1115),
  delete nodes sdb:select-node($doc, 1115),
  delete nodes sdb:select-node($doc, 1160),
  delete nodes sdb:select-node($doc, 1160),
  delete nodes sdb:select-node($doc, 1160),
  delete nodes sdb:select-node($doc, 1160),
  delete nodes sdb:select-node($doc, 1205),
  delete nodes sdb:select-node($doc, 1205),
  delete nodes sdb:select-node($doc, 1205),
  delete nodes sdb:select-node($doc, 1205),
  delete nodes sdb:select-node($doc, 1250),
  delete nodes sdb:select-node($doc, 1250),
  delete nodes sdb:select-node($doc, 1250),
  delete nodes sdb:select-node($doc, 1250),
  delete nodes sdb:select-node($doc, 1295),
  delete nodes sdb:select-node($doc, 1295),
  delete nodes sdb:select-node($doc, 1295),
  delete nodes sdb:select-node($doc, 1295),
  delete nodes sdb:select-node($doc, 1340),
  delete nodes sdb:select-node($doc, 1340),
  delete nodes sdb:select-node($doc, 1340),
  delete nodes sdb:select-node($doc, 1340),
  delete nodes sdb:select-node($doc, 1385),
  delete nodes sdb:select-node($doc, 1385),
  delete nodes sdb:select-node($doc, 1385),
  delete nodes sdb:select-node($doc, 1385),
  delete nodes sdb:select-node($doc, 1430),
  delete nodes sdb:select-node($doc, 1430),
  delete nodes sdb:select-node($doc, 1430),
  delete nodes sdb:select-node($doc, 1430),
  delete nodes sdb:select-node($doc, 1475),
  delete nodes sdb:select-node($doc, 1475),
  delete nodes sdb:select-node($doc, 1475),
  delete nodes sdb:select-node($doc, 1475),
  delete nodes sdb:select-node($doc, 1520),
  delete nodes sdb:select-node($doc, 1520),
  delete nodes sdb:select-node($doc, 1520),
  delete nodes sdb:select-node($doc, 1520),
  delete nodes sdb:select-node($doc, 1565),
  delete nodes sdb:select-node($doc, 1565),
  delete nodes sdb:select-node($doc, 1565),
  delete nodes sdb:select-node($doc, 1565),
  delete nodes sdb:select-node($doc, 1610),
  delete nodes sdb:select-node($doc, 1610),
  delete nodes sdb:select-node($doc, 1610),
  delete nodes sdb:select-node($doc, 1610),
  delete nodes sdb:select-node($doc, 1655),
  delete nodes sdb:select-node($doc, 1655),
  delete nodes sdb:select-node($doc, 1655),
  delete nodes sdb:select-node($doc, 1655),
  rename node sdb:select-node($doc, 1700) as <sheetData/>,
  delete nodes sdb:select-node($doc, 1700),
  delete nodes sdb:select-node($doc, 1700),
  delete nodes sdb:select-node($doc, 1700),
  delete nodes sdb:select-node($doc, 1700),
  delete nodes sdb:select-node($doc, 1700),
  delete nodes sdb:select-node($doc, 1700),
  insert nodes <row spans="1:4" r="2" x14ac:dyDescent="0.25"><c r="A2" t="s"><v>11</v></c><c r="B2" t="s"><v>15</v></c><c r="C2" t="s"><v>12</v></c><c r="D2" t="s"><v>13</v></c></row> before sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  insert nodes <row spans="1:4" r="3" x14ac:dyDescent="0.25"><c r="A3" t="s"><v>14</v></c><c r="B3" t="s"><v>20</v></c><c r="C3" t="s"><v>23</v></c><c r="D3" t="s"><v>26</v></c></row> before sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  insert nodes <row spans="1:4" r="4" x14ac:dyDescent="0.25"><c r="A4" t="s"><v>14</v></c><c r="B4" t="s"><v>21</v></c><c r="C4" t="s"><v>23</v></c><c r="D4" t="s"><v>25</v></c></row> before sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  insert nodes <row spans="1:4" r="5" x14ac:dyDescent="0.25"><c r="A5" t="s"><v>14</v></c><c r="B5" t="s"><v>22</v></c><c r="D5" t="s"><v>24</v></c></row> before sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  rename node sdb:select-node($doc, 1707) as <pageMargins/>,
  insert node attribute right { 0.7 } into sdb:select-node($doc,1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1707),
  delete nodes sdb:select-node($doc, 1713),
  delete nodes sdb:select-node($doc, 1713)
)

**Comment by JohannesLichtenberger** [comment]
Okay, fixed another bug in Sirix in my diffing algorithm with the duplicated node-IDs (sdb:select-node($node as xs:node, $nodeKey as xs:integer))

**Comment by JohannesLichtenberger** [comment]
Ah sorry, completely my fault...
