### ISSUE TITLE
Bug in XQuery Update / rename expression

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sebbae/brackit#8]
Hi Sebastian,

there seems to be a bug in the rename node expression:

let $doc := sdb:doc('path1','shredded', 1)
return (
  replace node sdb:select-node($doc, 4) with <revision date="4.03.2019" location="Etzels Hof" user=" Dietrich von Bern"/>,
  rename node sdb:select-node($doc, 15) as row,
  insert node attribute Value { 12 } into sdb:select-node($doc,15),
  delete nodes sdb:select-node($doc, 19),
  replace value of node sdb:select-node($doc, 16) with "MUELLER",
  replace value of node sdb:select-node($doc, 20) with "2600,00",
  rename node sdb:select-node($doc, 27) as row,
  replace value of node sdb:select-node($doc, 32) with "2800,00",
  rename node sdb:select-node($doc, 33) as row,
  insert node attribute Value { 15 } into sdb:select-node($doc,33),
  delete nodes sdb:select-node($doc, 37)
)

org.brackit.xquery.QueryException: err:XPDY0002: Dynamic context variable fs:dot is not assigned a value
	at org.brackit.xquery.expr.DefaultCtxItem.evaluateToItem(DefaultCtxItem.java:95)
	at org.brackit.xquery.expr.DefaultCtxItem.evaluate(DefaultCtxItem.java:78)
	at org.brackit.xquery.expr.StepExpr.evaluate(StepExpr.java:69)
	at org.brackit.xquery.expr.StepExpr.evaluateToItem(StepExpr.java:190)
	at org.brackit.xquery.update.Rename.evaluateToItem(Rename.java:117)
	at org.brackit.xquery.update.Rename.evaluate(Rename.java:69)
	at org.brackit.xquery.expr.SequenceExpr$EvalSequence.sequence(SequenceExpr.java:69)
	at org.brackit.xquery.sequence.FlatteningSequence$FlatteningIter.next(FlatteningSequence.java:64)
	at org.brackit.xquery.sequence.FlatteningSequence$FlatteningIter.next(FlatteningSequence.java:56)
	at org.brackit.xquery.expr.PipeExpr$PipeSequence$1.next(PipeExpr.java:81)
	at org.brackit.xquery.XQuery.run(XQuery.java:90)
	at org.brackit.xquery.XQuery.execute(XQuery.java:69)

I think the step expression might not be right, but I don't really know.

**Comment by JohannesLichtenberger** [comment]
Shit, I think it's again my faulty XQuery Update Script, which I'm generating in an XQuery diff-function ;-)

I feel really sorry... closing this I guess ;)

**Comment by JohannesLichtenberger** [comment]
Yes, just checked, the rows must be in quotes for sure...
